### PR TITLE
Enable custom ID generation

### LINKED ISSUE #68: Proposal for custom ID generation
### Overview
Allow a user to specify a custom function for ID generation. The current ID generation function would be the default implementation and the only one provided by zetteldeft itself.

This is a pretty "light touch" proposal, intended to add flexibility without complexity.

### Background
I like timestamp-based IDs; they make good sense for notes. My use case for this proposal comes from "upgrading" existing notes to be zetteldeft notes (having IDs). When assigning an ID to an existing note, I'd prefer the timestamp be based on the file's create date/time, rather than the current time.

My use case is half addressed by the patch I posted [here][1] for #63, which has Zetteldeft's rename function automatically generate an ID if one isn't present. Simple enough. What remains is to allow a user-specified ID generation function to be used.

### Proposed Approach
1. Make `zetteldeft-generate-id` a custom variable that points to a function. Document that the function must accept optional arguments for title and (existing) file path; this enables an implementing function to consider all available note attributes when generating the ID.
2. Rename the current ID generation function to `zetteldeft-generate-id-from-current-time` (or similar), and update its argument signature. The function body would stay the same.
3. Make `zetteldeft-generate-id-from-current-time` (or whatever we name this) the default value for `zetteldeft-generate-id`.
4. When creating a new note, pass title as an argument to `zetteldeft-generate-id`.
5. When renaming an existing note, pass title and file path as arguments to `zetteldeft-generate-id`.

The default implementation will ignore the additional arguments. Custom implementations may use these however they like (including examining file system metadata, or reading the file and parsing its contents).

### Additional Thoughts

The output of a custom ID generation function could be anything. It would be up to the user to ensure the ID regex is compatible, just as it is currently.

This may be sufficient to address #66 as well...or at least allow someone to have a go at this.

[1]: https://github.com/jeffvalk/zetteldeft/commit/da60afb3d47c2afa22de8aac36e98f4c0b4b523a

### PR DESCRIPTION
**Pull request by jeffvalk**
Closes #68

### CODE REVIEW

**Comment by EFLS** [comment]
Looking really nice! Thanks for including elaborate documentation in the `.org`. I'll take a closer look one of these days and play around with the new code.

**Comment by jeffvalk** [comment]
Good documentation is a good thing. :slightly_smiling_face: 

The example code in the `.org` should provide everything needed to play with the updated code. And unless the user sets the `zetteldeft-custom-id-function` variable, behavior remains completely unchanged.

**Comment by EFLS** [comment]
One question: is there any reason `title` is not an optional argument in the new `zetteldeft-generate-id`?

**Comment by EFLS** [comment]
Also, when thinking about Luhmann-style IDs (as discussed in #66), what makes most sense to use as input for a new ID, is the ID of its parent: in such a system, every note branches from an existing note.

I'm wondering whether (and how) configuring something like that would be possible with the current system.
Not yet, I think?

(To be clear: this doesn't need to be part of the current PR, I'm simply thinking about future ideas.)

**Comment by jeffvalk** [comment]
> is there any reason `title` is not an optional argument in the new `zetteldeft-generate-id`?

Yes. This guarantees that a custom ID function will always have all available information about a note when creating its ID. In zetteldeft's current design, `title` is always known when `zetteldeft-generate-id`is called, and hence not optional.

**Comment by jeffvalk** [comment]
> Also, when thinking about Luhmann-style IDs (as discussed in #66), what makes most sense to use as input for a new ID, is the ID of its parent: in such a system, every note branches from an existing note.

Yes, that makes sense.

> I'm wondering whether (and how) configuring something like that would be possible with the current system
> Not yet, I think? As this would rely on where and how a new note is created, which currently can't be taken into account by the new `zetteldeft-generate-id` function.

This would introduce a new dimension to note creation. To accommodate this, we could simply add an optional `parent-id` argument to `zetteldeft-generate-id`.

**Comment by EFLS** [comment]
> To accommodate this, we could simply add an optional parent-id argument to zetteldeft-generate-id.

Good to hear. But then the functions to create new files would require an overhaul too -- and there are still some questions related to such "branching" types of notes (for example, branching only makes sense when creating a new note from an existing one). Let's leave that for a separate discussion.

Thanks for your useful contribution!

**Comment by jeffvalk** [comment]
> > To accommodate this, we could simply add an optional parent-id argument to zetteldeft-generate-id.
> 
> Good to hear. But then the functions to create new files would require an overhaul too -- and there are still some questions related to such "branching" types of notes (for example, branching only makes sense when creating a new note from an existing one). Let's leave that for a separate discussion.

If kept simple, it could be done without altering the existing "create note" functions. But yes, this discussion is better left for #66.

> 
> Thanks for your useful contribution!

Of course!

**Pull request merged**
