### PR TITLE
Update zettedeft-find-file, use non-matching input as new file title

### LINKED ISSUE #115: Disable defaulting to find-file when the file is not found in the deft folder
Hi, I asked earlier in the Deft package page (no answers yet) about being able to disable defaulting to find-file when the file is not found in the deft folder, so a new file is created using deft-new-file-format template for creating new notes. I was wondering if this is possible.

### PR DESCRIPTION
**Pull request by localauthor**
Fix #115 

Adds option to use input as title for a new note.

cc: @iburunat

### CODE REVIEW

**Comment by EFLS** [comment]
Looks useful, thanks.

I'm trying to understand the code you added, could you explain what the following is meant for?

```emacs-lisp
  (let* ((dir (expand-file-name deft-directory)))
    (unless (string-match (concat "^" dir) file)
      (setq file (concat dir "/" file)))
```

**Comment by EFLS** [comment]
Ah okay, that makes sense. Thanks for the clarification

**Comment by iburunat** [comment]
Thanks, another improvement to this could be to have the same title-prefix, -suffix, and id-format as a the standard Zetteldeft note, so it's formatted exactly like any other Zetteldeft note.

**Comment by localauthor** [comment]
It should do this already, since it uses`zetteldeft-new-note` to create the new note, and that's what `zetteldeft-new-note` does. Is it not working that way?

**Comment by iburunat** [comment]
It doesn't work like that on my end. What is `zetteldeft-new-note`? I can't find this variable.

**Comment by localauthor** [comment]
Sorry, the function is actually `zetteldeft-new-file`

**Comment by iburunat** [comment]
Thanks, weirdly enough, it's not working as it should, and I am using the updated package... it creates a blank file, without all the settings I have set for new files, such as `(setq zetteldeft-title-prefix "#+TITLE: ")` and `(setq zetteldeft-title-suffix "\n#+STARTUP: overview, indent\n#+LAST_MODIFIED:\n\n")`.

**Pull request merged**
